from datetime import datetime

from geoalchemy2 import Geometry
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from database import Base


# ============================================================
# AI EVENTS
# ============================================================

class AIEvent(Base):
    """
    Stores raw AI detection events received from buses.

    Each event_id must be globally unique to prevent duplicate
    processing of the same AI detection.
    """

    __tablename__ = "ai_events"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    # Unique ID generated by the AI system
    event_id = Column(
        String,
        unique=True,
        nullable=False,
        index=True,
    )

    # Bus that generated the event
    bus_id = Column(
        String,
        nullable=False,
        index=True,
    )

    # Example: pothole, garbage, accident, flooding
    event_type = Column(
        String,
        nullable=False,
        index=True,
    )

    # LOW / MEDIUM / HIGH / CRITICAL
    severity = Column(
        String,
        default="MEDIUM",
        nullable=False,
        index=True,
    )

    latitude = Column(
        Float,
        nullable=False,
    )

    longitude = Column(
        Float,
        nullable=False,
    )

    # AI confidence: 0.0 - 1.0
    confidence = Column(
        Float,
        nullable=False,
    )

    # Reference to image/video/evidence
    evidence_url = Column(
        Text,
        nullable=True,
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    # Whether backend processing is complete
    processed = Column(
        Boolean,
        default=False,
        nullable=False,
    )


# ============================================================
# INCIDENTS
# ============================================================

class Incident(Base):
    """
    Represents a verified or potentially verified urban incident.

    Multiple AI events from different buses can confirm the same
    physical incident through spatial matching.
    """

    __tablename__ = "incidents"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    event_type = Column(
        String,
        nullable=False,
        index=True,
    )

    # LOW / MEDIUM / HIGH / CRITICAL
    severity = Column(
        String,
        default="MEDIUM",
        nullable=False,
        index=True,
    )

    latitude = Column(
        Float,
        nullable=False,
    )

    longitude = Column(
        Float,
        nullable=False,
    )

    # PostGIS geographic point
    location = Column(
        Geometry(
            geometry_type="POINT",
            srid=4326,
            spatial_index=True,
        ),
        nullable=False,
    )

    # NEW → UNDER_REVIEW → IN_PROGRESS → RESOLVED
    status = Column(
        String,
        default="NEW",
        nullable=False,
        index=True,
    )

    confirmation_count = Column(
        Integer,
        default=0,
        nullable=False,
    )

    unique_bus_count = Column(
        Integer,
        default=0,
        nullable=False,
    )

    average_confidence = Column(
        Float,
        default=0.0,
        nullable=False,
    )

    verification_score = Column(
        Float,
        default=0.0,
        nullable=False,
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    confirmations = relationship(
        "IncidentConfirmation",
        back_populates="incident",
        cascade="all, delete-orphan",
    )

    status_history = relationship(
        "IncidentStatusHistory",
        back_populates="incident",
        cascade="all, delete-orphan",
    )


# ============================================================
# INCIDENT CONFIRMATIONS
# ============================================================

class IncidentConfirmation(Base):
    """
    Links an AI event to the incident it created or confirmed.
    """

    __tablename__ = "incident_confirmations"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    incident_id = Column(
        Integer,
        ForeignKey("incidents.id"),
        nullable=False,
        index=True,
    )

    event_id = Column(
        String,
        ForeignKey("ai_events.event_id"),
        nullable=False,
        index=True,
    )

    bus_id = Column(
        String,
        nullable=False,
        index=True,
    )

    confidence = Column(
        Float,
        nullable=False,
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    incident = relationship(
        "Incident",
        back_populates="confirmations",
    )

    __table_args__ = (
        UniqueConstraint(
            "incident_id",
            "event_id",
            name="unique_incident_event",
        ),
    )


# ============================================================
# INCIDENT STATUS HISTORY
# ============================================================

class IncidentStatusHistory(Base):
    """
    Stores the status transition history of an incident.
    """

    __tablename__ = "incident_status_history"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    incident_id = Column(
        Integer,
        ForeignKey("incidents.id"),
        nullable=False,
        index=True,
    )

    old_status = Column(
        String,
        nullable=True,
    )

    new_status = Column(
        String,
        nullable=False,
    )

    changed_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    incident = relationship(
        "Incident",
        back_populates="status_history",
    )


# ============================================================
# BUSES
# ============================================================

class Bus(Base):
    """
    Stores the latest known location and status of each bus.
    """

    __tablename__ = "buses"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    bus_id = Column(
        String,
        unique=True,
        nullable=False,
        index=True,
    )

    latitude = Column(
        Float,
        nullable=False,
    )

    longitude = Column(
        Float,
        nullable=False,
    )

    # PostGIS geographic point
    location = Column(
        Geometry(
            geometry_type="POINT",
            srid=4326,
            spatial_index=True,
        ),
        nullable=False,
    )

    last_seen = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    is_active = Column(
        Boolean,
        default=True,
        nullable=False,
    )